set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
set exrc
set relativenumber
set number
set nohlsearch
set incsearch
set noswapfile
set nobackup
set undofile
set undodir=~/.local/share/nvim/undo
set noerrorbells
set nowrap
set hidden
set scrolloff=8
set colorcolumn=80
set signcolumn=yes
set mouse=a
set termguicolors
set cursorline
set formatoptions-=cro
set completeopt=menu,menuone,noselect
set splitbelow
set splitright
