#! /bin/sh
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr
setxkbmap -option caps:none
setxkbmap -option caps:ctrl_modifier

# Autostart
killall emacs
emacs --daemon
pgrep -x sxhkd > /dev/null || sxhkd &
killall picom
picom &
$HOME/.config/polybar/launch.sh
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x dropbox > /dev/null || dropbox &
pgrep -x lxpolkit > /dev/null || lxpolkit &
pgrep -x light-locker || light-locker &
killall dunst 
dunst &

# Figure out a better way to do this
# bspc monitor HDMI-0 -d 1 2 3 4 5
# bspc monitor DP-4 -d 6 7 8 9 0
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0


bspc config border_width 4
bspc config window_gap 12
bspc config focused_border_color     "#b16286"
bspc config normal_border_color      "#282828"

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a KeePassXC desktop='^2' follow=on focus=on
bspc rule -a Spotify desktop='^3' follow=on focus=on
bspc rule -a ncspot desktop='^3' follow=on focus=on
bspc rule -a discord desktop='^4' follow=on focus=on
bspc rule -a obs desktop='^5' follow=on focus=on
bspc rule -a "VirtualBox Manager" desktop='^6' follow=on focus=on state=floating
bspc rule -a Lutris desktop='^7' follow=on focus=on state=floating
bspc rule -a Alacritty desktop='^8' follow=on focus=on
bspc rule -a VSCodium desktop='^8' follow=on focus=on
bspc rule -a firefox desktop='^9' follow=on focus=on
bspc rule -a Thunar desktop='^10' follow=on focus=on
bspc rule -a Emacs desktop='^8' follow=on focus=on state=tiled

# Wallpaper
feh --bg-fill $HOME/Pictures/Wallpapers/gavin_odonnel/2.jpg
